language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "node_modules"
before_install:
- chmod +x mvnw
before_script:
- "npm install"
- "npm run build:prod"
script:
- "./mvnw clean"
- "./mvnw package -DskipTests"
branches:
  only:
  - master
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: script
  script:
  - "./mvnw heroku:deploy -DskipTests"
  on:
    branch: master
  skip_cleanup: true
